name = "curve-gauge-api"
main = "worker.js"
compatibility_date = "2025-06-01"

[[kv_namespaces]]
binding = "CURVE_GAUGES"
id = "7a78c42f64da462fb60fcff248358300"

[env.production.vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true



